### ISSUE TITLE
Block commands per-server

### ISSUE THREAD

**Issue by literalplus** [xxyy/commandblockerultimate#10]
With the bungee plugin, it should be possible to block commands specifically per-server. So, for instance, you want to block `/help` on `pvp`, but not on `kitpvp`.

Configuration could be implemented like this:

``` yaml
per-server-blocked:
  - pvp:
    - help
    - kill
  - plots:
    - -pl #allows /pl on this server
```

As requested here: http://www.spigotmc.org/threads/command-blocker-ultimate.9602/#post-405366
