### ISSUE TITLE
Only console commands

### ISSUE THREAD

**Issue by Twonox** [xxyy/commandblockerultimate#22]
Could you add only console commands system ?
The operators can't use defined commands.

**Comment by Twonox** [comment]
And why not a separate commands list with a different message like nocheatplus.

**Comment by xxyy** [comment]
Hi,

thanks for your report. Could you elaborate what you mean? From my
understanding, you want an option that allows the console to bypass command
blocks. The command blocker doe's not apply to console as far as I can
remember.

Also, I have no idea what you are trying to say with second post. Please
open a separate issue for that and clearly explain what you would like to
see.

Best regards

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.

**Comment by Twonox** [comment]
```
protection:
  plugins:
    hide:
      active: true
      nopermission:
        message: '&cI''m sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.'
        commands:
        - plugins
        - version
        - icanhasbukkit
      unknowncommand:
        message: Unknown command. Type "/help" for help.
        commands:
        - bukkit:version
        - bukkit:plugins
  commands:
    consoleonly:
      active: false
      message: '&cI''m sorry, but this command can''t be executed in chat. Use the console instead!'
      commands:
      - op
      - deop
```
It's NoCheatPlus feature. We can set an other message with a secondary list of commands.

> message: '&cI''m sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.'
> message: 'Unknown command. Type "/help" for help.'

And we can block commands for operators IG. (/op and /deop are executable only with console)

> message: '&cI''m sorry, but this command can''t be executed in chat. Use the console instead!'

Thus, could you do same thing with your plugins please ?
I wouldn't use NCP but this command blocker feature is only in this plugins, so if you add this to your plugins I can remove NCP from my server with not problems.
